name: NPM Delete release

on:
  release:
    types: [deleted]

jobs:
  delete_release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node_version: 14
        registry_url: https://registry.npmjs.org/
    - run: npm unpublish migrate-mongoose-ts@${{ github.event.release.tag_name }}
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}